config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  mount Sidekiq::Web => '/sidekiq'


  root to: 'pages#home'
  get '/contact-us', to: 'pages#contact'

  get '/health-check', to: 'application#health'
  patch '/recipes/:recipe_id/images/:id/featured', to: 'recipes/images#featured'

  devise_for :users, skip: :all, skip_helpers: true

  devise_scope :user do
    resources :registrations, only: [:new, :create, :update, :edit]
    resources :sessions, only: [:create, :new, :destroy]
    resources :passwords, only: [:create, :new, :update]
    resources :confirmations, only: [:create, :new]
  end

  resources :recipes, only: [:create, :destroy, :edit, :index, :new, :show, :update] do
    scope module: :recipes do
      resources :images, only: [:update, :destroy]
      resources :parsed_lines, only: [:update]
      resources :ingredients, only: [:create]
      resources :tools, only: [:create]
      resources :steps, only: [:update]
    end
  end

  resource :account, only: [:show, :edit, :update]

  namespace :api do
    namespace :v1 do
      resources :me, only: [:index]
      resources :web_recipes, only: [:create, :show]

      resources :recipes do
        scope module: :recipes do
          resources :images, only: [:create]
        end
      end
    end
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  searchkick
  has_many :images, dependent: :destroy, as: :attachable

  has_many :ingredients, dependent: :destroy
  has_many :parsed_lines, dependent: :destroy
  has_many :parsed_long_lines, dependent: :destroy
  has_many :steps, dependent: :destroy
  has_many :tools, dependent: :destroy

  belongs_to :web_recipe, optional: true, dependent: :destroy
  belongs_to :user, optional: true

  scope :with_attached_images, -> { includes(:images).merge(Image.with_attached_file) }
end

app/controllers/api/v1/recipes/images_controller.rb
class Api::V1::Recipes::ImagesController < ApplicationController
  before_action :authenticate_user!

  protect_from_forgery with: :exception, except: [:create], prepend: true

  def create
    image_json_array = []

    if params[:imageDataArray].kind_of?(Array)
      image_json_array = JSON.parse(params[:imageDataArray].to_json)
    else
      image_json_array = JSON.parse(params[:imageDataArray])
    end

    RecipeImagesImporterWorker.perform_async(image_json_array, params[:recipe_id])

    render json: {message: 'currently importing', success: true}
  end

  private

  def recipe_params
    params.permit(:imageDataArray)
  end
end

app/controllers/recipes/images_controller.rb
module Recipes
  class ImagesController < ApplicationController
    def update
      ImageTextParserWorker.perform_async(params[:id])

      redirect_to edit_recipe_path(params[:recipe_id])
    end

    def featured
      recipe = Recipe.find(params[:recipe_id])
      recipe.images.update_all(featured: false)

      image = Image.find(params[:id])
      image.update(featured: true)

      redirect_to recipe_path(params[:recipe_id])
    end

    def destroy
      image = Image.find(params[:id])

      if image.present?
        image.destroy
      end

      redirect_to recipe_path(params[:recipe_id])
    end
  end
end

app/controllers/recipes/ingredients_controller.rb
module Recipes
  class IngredientsController < ApplicationController
    protect_from_forgery with: :exception, except: [:create], prepend: true

    def create
      ingredients = ingredients_params.map do |ingredient|
        {
          content: ingredient[:content],
          recipe_id: ingredient[:recipe_id],
          created_at: Time.now.utc,
          updated_at: Time.now.utc
        }
      end

      ParsedLine.where(id: parsed_lined_ids_params).update_all(deleted: true)
      Ingredient.insert_all(ingredients)

      render json: {success: true}
    end

    def destroy
      ingredient = Ingredient.find(params[:id])
      ingredient.update(deleted: true)

      redirect_to edit_recipe_path(params[:recipe_id])
    end

    def update
      ingredient = Ingredient.find(params[:id])

      if ingredient
        ingredient.update(content: ingredient_params[:ingredient][:content])

        redirect_to edit_recipe_path(params[:recipe_id])
      else
        redirect_to edit_recipe_path(params[:recipe_id])
      end
    end

    private

    def ingredient_params
      params.permit(ingredient: [:content])
    end

    def ingredients_params
      params.permit(ingredients: [:content, :recipe_id])[:ingredients]
    end

    def parsed_lined_ids_params
      params.permit(parsed_line_ids: [])[:parsed_line_ids]
    end
  end
end

app/controllers/recipes/parsed_lines_controller.rb
module Recipes
  class ParsedLinesController < ApplicationController
    def update
      params[:type].constantize.update(params[:id], deleted: true)

      redirect_to edit_recipe_path(params[:recipe_id])
    end
  end
end

app/controllers/recipes/steps_controller.rb
module Recipes
  class StepsController < ApplicationController
    protect_from_forgery with: :exception, except: [:create], prepend: true

    def update
      updater = StepUpdater.new({
        id: params[:id],
        attributes: step_params.merge(image: params[:step][:image]),
        parsed_line_model_constant: ParsedLine,
        parsed_line_ids: parsed_line_ids_params,
        step_model_constant: Step,
        step_image_saver_constant: StepImageSaver,
        step_saver_factories: [StepOne, StepUpdate, StepCreate]
      })

      updater.run

      render json: {success: true}
    end

    def create
      creator = StepCreate.new(
        params[:id],
        step_params,
        Step
      )

      creator.save

      ParsedLine
        .where(id: parsed_line_ids_params)
        .update_all(deleted: true)

      render json: {success: true}
    end

    def destroy
      step = Step.find(params[:id])
      step.update(deleted: true)

      redirect_to edit_recipe_path(params[:recipe_id])
    end

    private

    def step_params
      params.require(:step).permit(:content, :recipe_id, :title, :position)
#      params.permit(step: [:content, :recipe_id, :title, :image, :position], image: {})
    end

    def parsed_line_ids_params
      params.permit(parsed_line_ids: [])[:parsed_line_ids]
    end
  end
end

app/controllers/recipes/tips_controller.rb
module Recipes
  class TipsController < ApplicationController
    protect_from_forgery with: :exception, except: [:create], prepend: true

    def create
      ParsedLine.where(id: parsed_lined_ids_params).update_all(deleted: true)
      Tip.create(content: tip_params["tip"]["content"], recipe_id: params["recipe_id"])

      render json: {success: true}
    end

    def destroy
      tip = Tip.find(params[:id])
      tip.update(deleted: true)

      redirect_to edit_recipe_path(params[:recipe_id])
    end

    def update
      tip = Tip.find(params[:id])

      if tip
        tip.update(content: tip_params[:tip][:content])

        redirect_to edit_recipe_path(params[:recipe_id])
      else
        redirect_to edit_recipe_path(params[:recipe_id])
      end
    end

    private

    def tip_params
      params.permit(tip: [:content])
    end

    def tips_params
      params.permit(tips: [:content, :recipe_id])[:tips]
    end

    def parsed_lined_ids_params
      params.permit(parsed_line_ids: [])[:parsed_line_ids]
    end
  end
end

app/controllers/recipes/tools_controller.rb
module Recipes
  class ToolsController < ApplicationController
    protect_from_forgery with: :exception, except: [:create], prepend: true

    def create
      tools = tools_params.map do |tool|
        {
          content: tool[:content],
          recipe_id: tool[:recipe_id],
          created_at: Time.now.utc,
          updated_at: Time.now.utc
        }
      end

      ParsedLine.where(id: parsed_lined_ids_params).update_all(deleted: true)
      Tool.insert_all(tools)

      render json: {success: true}
    end

    def update
      tool = Tool.find(params[:id])

      if tool
        tool.update(content: tool_params[:tool][:content])

        redirect_to edit_recipe_path(params[:recipe_id])
      else
        redirect_to edit_recipe_path(params[:recipe_id])
      end
    end

    private

    def tool_params
      params.permit(tool: [:content])
    end

    def tools_params
      params.permit(tools: [:content, :recipe_id])[:tools]
    end

    def parsed_lined_ids_params
      params.permit(parsed_line_ids: [])[:parsed_line_ids]
    end
  end
end

app/controllers/recipes_controller.rb
require 'open-uri'

class RecipesController < ApplicationController
  include Pagy::Backend

  before_action :authenticate_user!, :except => [:index, :show]

  def create

    url_validator = UrlValidator.new(params[:web_recipe][:url])

    if url_validator.valid?
      uri = url_validator.value

      html_response_body_string = Net::HTTP.get_response(uri).body

      parser = HtmlPageParser.new(
        html_response_body_string,
        Nokogiri::HTML(html_response_body_string)
      )


      name = uri.path + uri.host

      web_recipe = WebRecipe.find_by_name(name)

      @image_sources = parser.query_image_sources

      if web_recipe
        redirect_to recipe_path(web_recipe.recipe, web_recipe_url: params[:web_recipe][:url])
      else

        new_web_recipe = WebRecipe.create({
          content: parser.inner_text,
          host_origin: uri.host,
          name: name,
          pathname: uri.path
        })

        @recipe = Recipe.create(
          title: new_web_recipe.pathname.parameterize.gsub(/-/, ' ').titleize,
          web_recipe_id: new_web_recipe.id,
          full_text: new_web_recipe.content.gsub(/(\R)(?:\s*\R)+/, '\1'),
          user_id: current_user.id
        )

        redirect_to edit_recipe_path(@recipe, web_recipe_url: params[:web_recipe][:url])
      end
    else
      redirect_to new_recipe_path, flash: { error: 'Invalid URL' }
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])

    if current_user.id == @recipe.user_id && @recipe.web_recipe.present?

      url_validator = [
        UrlValidator.new(params[:web_recipe_url]),
        UrlValidator.new(
          "https://#{@recipe.web_recipe.host_origin}#{@recipe.web_recipe.pathname}"
        )
      ].find(&:valid?)



      if url_validator
        html_response_body_string = Net::HTTP.get_response(url_validator.value).body

        parser = HtmlPageParser.new(
          html_response_body_string,
          Nokogiri::HTML(html_response_body_string)
        )

        @image_sources = parser.query_image_sources
      end

      @text = []
    else
      flash[:error] = "You do not have permissions to edit this recipe"
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    if current_user.id == @recipe.user_id
      @recipe.destroy

      redirect_to recipes_path
    else
      flash[:error] = "You do not have permissions to delete this recipe"
      redirect_to recipes_path
    end
  end

  def index
    @pagy, @recipes = pagy(
      Recipe.includes(:images).merge(
        Image.with_attached_file
      ).all.where(published_at: true).order(created_at: :desc)
    )

    if params[:search]
      @searched = Recipe.search(params[:search], page: params[:page], per_page: 20)
      @pagy_search = Pagy.new_from_searchkick(@searched)

    else
      @searched = []
    end
  end

  def new
    @recipe = WebRecipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def update
    recipe = Recipe.find(params[:id])
    if current_user.id == recipe.user_id
      recipe_updater = RecipeUpdater.new({
        recipe: recipe,
        recipe_attr: {
          published_at: true,
          description: params[:recipe][:description],
          full_text: params[:recipe][:full_text],
          title: params[:recipe][:title]
        },
        recipe_asset: params[:recipe][:images],
        recipe_image_saver: RecipeImageSaver,
        recipe_attributes_saver: RecipeAttributesSaver
      })

      updated_recipe = recipe_updater.coordinate

      redirect_to recipe_path(updated_recipe.id)
    else
      flash[:error] = 'You do not have permissions to update this recipe'
      redirect_to recipes_path
    end
  end


end

app/views/recipes/edit.haml
%main.RecipeView.js-RecipeEditor{'data-recipe-id': @recipe.id}
  %h1 editing recipe
  %h2= link_to('View Recipe', recipe_path(@recipe.id))


  - if @image_sources.present?
    .RecipeView__web-images.flex.flex-row.flex-wrap{'data-web-images': ''}
      - @image_sources.each_with_index do |image_source, index|
        = image_tag url_for(image_source), alt: "#{@recipe.title} - #{index}", class: 'RecipeView__web-image w-2/4'
    %button
      = link_to 'Save Images', '#', {'data-save-web-image': ''}

  = form_with(model: @recipe, method: "patch", class: 'RecipeView__form ') do |form|
    = form.label(:title, "Title")
    = form.text_field(:title)
    = form.label(:full_text, "Full Text")
    = form.text_area(:full_text)
    = form.label(:date_published, "Date Published")
    = form.date_field(:date_published)
    = form.submit("update")


  %button
    = link_to 'Delete Recipe', recipe_path(@recipe), data: {confirm: 'Are you sure?'}, method: :delete 


  .RecipeView__images-container
    - @recipe.images.with_attached_file.each do |image|
      .RecipeView__image-container
        = image_tag url_for(image.file)
        = link_to 'Delete Image', recipe_image_path(@recipe, image), data: {confirm: 'Are you sure?'}, method: :delete 
        - if image.featured.blank?
          = link_to 'Make Featured', "/recipes/#{@recipe.id}/images/#{image.id}/featured", method: :patch 

app/views/recipes/index.haml
.recipes-searched.flex.flex-col.justify-center.items-center.my-0.m-auto
  .search--form
    = form_tag recipes_path, method: :get, class: "RecipesList__search-input w-full", role: "search" do
      = text_field_tag :search, params[:search], class: ""
      = submit_tag "Search", name: nil, class: "btn btn-default"

  %ul.flex.flex-wrap
    - @searched.each do |recipe|
      %li.p-4.text-lg
        = link_to(recipe_path(recipe.id)) do
          .card
            - featured = recipe.images.find { |img| img.featured }
            - if featured
              .featured-img.max-w-sm
                = image_tag url_for(featured.file)
              .title
                = recipe.title

  - if @pagy_search.present?
    = pagy_nav(@pagy_search).html_safe

.recipes-container.my-0.m-auto.max-w-screen-xl
  - if @pagy_search.blank?
    .recipes.flex.flex-col.justify-center.items-center.-mt-0.m-auto.mb-40
      %ul.flex.flex-wrap
        - @recipes.each_with_index do |recipe, index|
          %li.p-4.text-lg
            = link_to(recipe_path(recipe.id)) do
              .card
                - featured = recipe.images.find { |img| img.featured }
                - if featured
                  .featured-img
                    = image_tag url_for(featured.file)
                .title
                  = recipe.title


      - if @pagy.present?
        = pagy_nav(@pagy).html_safe

app/views/recipes/new.haml
%main.recipes
  .container-center.w-full.m-auto
    %h1 Paste recipe URL below and click create:
    = form_for(:web_recipe, url: "/recipes", method: 'post', html: {class: 'w-full flex flex-col'} ) do |form|
      = form.label(:url, "URL")
      = form.text_field(:url, class: 'w-full border-solid	border-gray-500 border p-4', required: true)
      = form.submit("create", class: 'p-4 m-auto my-4')

app/views/recipes/show.haml
%main.RecipeView.text-lg.js-RecipeShow{'data-recipe-id': @recipe.id}
  .RecipeView__header
  %h2= @recipe.title
  - if @recipe.web_recipe.present?
    = link_to("Visit Original recipe", @recipe.web_recipe.full_path, target: '_blank')
  - if current_user.present? && current_user.id == @recipe.user_id
    = link_to("Edit Recipe", edit_recipe_path(@recipe.id), class: 'button')

  .RecipeView__images-container{'data-images-container': ''}
    - @recipe.images.order(featured: :desc).with_attached_file.each do |image|
      .RecipeView__image-container.js-RecipeShow__image
        - if image.file.present? && image.file.attached?
          .actions.flex
            %button.js-rotate-left-btn
              Rotate Left
            %button.js-rotate-right-btn
              Rotate right
            %button.js-shrink
              Shrink
            %button.js-grow
              Grow
          = image_tag url_for(image.file), alt: image.alt_text, data: {'image-id' => image.id}
          - if current_user.id == @recipe.user_id
            = link_to 'Delete Image', recipe_image_path(@recipe, image), data: {confirm: 'Are you sure?'}, method: :delete 

          - if image.featured.blank? && current_user.id == @recipe.user_id 
            = link_to 'Make Featured', "/recipes/#{@recipe.id}/images/#{image.id}/featured", method: :patch 

  .RecipeView__full-text-container
    = @recipe.full_text