config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  mount Sidekiq::Web => '/sidekiq'


  root to: 'pages#home'
  get '/contact-us', to: 'pages#contact'

  get '/health-check', to: 'application#health'
  patch '/recipes/:recipe_id/images/:id/featured', to: 'recipes/images#featured'

  devise_for :users, skip: :all, skip_helpers: true

  devise_scope :user do
    resources :registrations, only: [:new, :create, :update, :edit]
    resources :sessions, only: [:create, :new, :destroy]
    resources :passwords, only: [:create, :new, :update]
    resources :confirmations, only: [:create, :new]
  end

  resources :recipes, only: [:create, :destroy, :edit, :index, :new, :show, :update] do
    scope module: :recipes do
      resources :images, only: [:update, :destroy]
      resources :parsed_lines, only: [:update]
      resources :ingredients, only: [:create]
      resources :tools, only: [:create]
      resources :steps, only: [:update]
    end
  end

  resource :account, only: [:show, :edit, :update]

  namespace :api do
    namespace :v1 do
      resources :me, only: [:index]
      resources :web_recipes, only: [:create, :show]

      resources :recipes do
        scope module: :recipes do
          resources :images, only: [:create]
        end
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blank_line.rb
class BlankLine
  def initialize(image_id, recipe_id, text)
    @image_id = image_id
    @recipe_id = recipe_id
    @text = text
  end

  def create
    {
      content: text.to_s.strip,
      recipe_id: recipe_id,
      image_id: image_id,
      created_at: Time.now.utc,
      updated_at: Time.now.utc
    }
  end

  def can_create?
    true
  end

  def is_long?
    false
  end

  def is_standard_length?
    false
  end

  def valid?
    false
  end

  private

  attr_accessor :image_id, :recipe_id, :text

end

app/models/image.rb
class Image < ApplicationRecord

  ActiveStorage::Attachment.after_create_commit do
    image = Image.includes(:attachable).find(self.record_id)

    RecipesChannel.broadcast_to(image.attachable, {
      recipe_id: image.attachable_id,
      image_id: image.id,
      alt_text: image.alt_text,
      url: self.service_url
    })
  end

  ALT_TEXT_CHAR_LIMIT = 250

  belongs_to :attachable, polymorphic: true

  has_many :parsed_lined

  has_one_attached :file

  def blob
    file.blob
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/line.rb
class Line
  def initialize(image_id, recipe_id, text)
    @image_id = image_id
    @recipe_id = recipe_id
    @text = text
  end

  def can_create?
    valid?
  end

  def create
    {
      content: text.strip,
      recipe_id: recipe_id,
      image_id: image_id,
      created_at: Time.now.utc,
      updated_at: Time.now.utc
    }
  end

  def is_long?
    false
  end

  def is_standard_length?
    true
  end

  def valid?
    trimmed  = text.to_s.strip
    trimmed.present? && trimmed.length <= 500
  end

  private

  attr_accessor :image_id, :recipe_id, :text

end

app/models/line_factory.rb
class LineFactory
  def initialize(line_text, options = {})
    @line_text = line_text

    @line_instances = [
      Line.new(options[:image_id], options[:recipe_id], line_text),
      LongLine.new(options[:image_id], options[:recipe_id], line_text),
      BlankLine.new(options[:image_id], options[:recipe_id], line_text)
    ]
  end

  def init
    line_instances.find { |line| line.can_create? }
  end

  private

  attr_accessor :line_text, :line_instances

end

app/models/lines.rb
class Lines
  attr_accessor :long, :standard

  def initialize(lines)
    @long = lines[:long]
    @standard = lines[:standard]
  end

end

app/models/long_line.rb
class LongLine
  def initialize(image_id, recipe_id, text)
    @image_id = image_id
    @recipe_id = recipe_id
    @text = text
  end

  def can_create?
    valid?
  end

  def create
    {
      content: text.strip,
      recipe_id: recipe_id,
      image_id: image_id,
      created_at: Time.now.utc,
      updated_at: Time.now.utc
    }
  end

  def is_long?
    true
  end

  def is_standard_length?
    false
  end

  def valid?
    trimmed  = text.to_s.strip
    trimmed.present? && trimmed.length > 500
  end

  private

  attr_accessor :image_id, :recipe_id, :text

end

app/models/null_user.rb
class NullUser

  def id
    0
  end

  def present?
    false
  end

  def valid_reset_password_link?
    false
  end
end

app/models/parsed_line.rb
class ParsedLine < ApplicationRecord
  belongs_to :recipe
  belongs_to :image, optional: true
end

app/models/parsed_long_line.rb
class ParsedLongLine < ApplicationRecord
  belongs_to :recipe
  belongs_to :image
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  searchkick
  has_many :images, dependent: :destroy, as: :attachable

  has_many :ingredients, dependent: :destroy
  has_many :parsed_lines, dependent: :destroy
  has_many :parsed_long_lines, dependent: :destroy
  has_many :steps, dependent: :destroy
  has_many :tools, dependent: :destroy

  belongs_to :web_recipe, optional: true, dependent: :destroy
  belongs_to :user, optional: true

  scope :with_attached_images, -> { includes(:images).merge(Image.with_attached_file) }
end

app/models/step.rb
class Step < ApplicationRecord
  DEFAULT_CONTENT_STRING = 'Enter step descripion here...'

  has_one :image, as: :attachable

  belongs_to :recipe
end

app/models/tip.rb
class Tip < ApplicationRecord
  belongs_to :recipe
end

app/models/tool.rb
class Tool < ApplicationRecord
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes

  def self.find_and_assign_by_reset_password(token)
    User.with_reset_password_token(token)&.tap do |user|
      user.reset_password_token = token
    end
  end

  def valid_reset_password_link?
    reset_password_token.present?
  end
end

app/models/web_recipe.rb
# frozen_string_literal: true

# app/models/web_recipe.rb
class WebRecipe < ApplicationRecord
  has_one :recipe

  def full_path
    "https://#{host_origin}#{pathname}"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def contact

  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
#
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/user_helper.rb
# frozen_string_literal: true
#
module UserHelper

  def devise_current_user

    @devise_current_user ||= (warden.authenticate(scope: :user) || NullUser.new)

  end

  def current_user
    if params[:user_id].blank?
      devise_current_user
    else
      @devise_current_user
    end
  end
end

app/views/layouts/_confirmation_callback.haml
- user = User.confirm_by_token(params[:confirmation_token])

- if user.errors.empty?
  .form--container-center
    %h2 Enter Password to confirm account
    = render partial: 'sessions/form', locals: {user: user}
- else
  %h1 Email was already confirmed, please try signing in

app/views/layouts/_navigation.haml
%header
  %h1.logo Logo
  %input#nav-toggle.nav-toggle{:type => "checkbox"}/
  %nav.nav-container
    %ul
      %li= link_to('Home', root_path)
      %li= link_to('Recipes', recipes_path)
      %li= link_to('Account', account_path)
      %li= link_to("Create", new_recipe_path)
      - if current_user.present?
        %li= button_to('Log Out', session_path(current_user.id), method: :delete, class: 'Account__tab')
      %li= link_to("Contact Us", contact_us_path)
  %label.nav-toggle-label{:for => "nav-toggle"}
    %span

app/views/layouts/_reset_password_callback.haml
- if user.valid_reset_password_link?
  .form--container-center
    %h3 Enter Your New Password
    %p
      Enter your new password for #{user.email}.

    = form_with model: user, url: password_path(user), method: :patch do |form|
      = form.hidden_field :reset_password_token
      = form.password_field :password

      = form.submit 'Confirm New Password'
- else
  %h1 Oops
  %p The password reset link provided was invalid, please try again.

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}

    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TheWholeEnchilada
    = action_cable_meta_tag
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag "application", "data-turbo-track": "reload"
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .modal.flex.hidden{ 'data-spinner-modal': ''}
      = image_pack_tag 'svgs/spinner.svg', class: 'spinner'
    %h2.flash-messages
      .text-green-700
        = flash[:success]
      .text-indigo-700
        = flash[:notice]
      .text-red-700
        = flash[:error]
      .text-yellow-700
        = flash[:alert]
    = render 'layouts/navigation'
    .content
      - if params[:reset_password_token]
        - user = User.find_and_assign_by_reset_password(params[:reset_password_token]) || NullUser.new
        = render partial: 'layouts/reset_password_callback', locals: {reset_password_token: params[:reset_password_token], user: user}
      - elsif params[:confirmation_token]
        = render 'layouts/confirmation_callback'
      - else
        = yield

app/views/pages/contact.haml
%main
  .container-center
    %h1.text-center 
      Feel free to email us at: info@thewholeenchilada.cc

app/views/pages/home.haml
%main.home
  .container-center
    %h1.text-center 
      = link_to("Welcome to The Whole Enchilada!", recipes_path)